### ISSUE TITLE
Can we remove the WTForm pip dependency?

### ISSUE THREAD

**Issue by securedirective** [CSE-Club/Website-Project#3]
Of the 19 pip dependencies, I found where we're using all but WTForm. We're using WTForms instead. Can we remove it?

**Comment by mkorcha** [comment]
Looks like some commit at some point dragged it in with `pip freeze`. It wouldn't exactly hurt to keep it but I'm not sure if anything else depends on it.

If you're ambitious and want to test it out feel free, but make sure your virtualenv is clear of all libraries installed by pip before you do so.

**Comment by securedirective** [comment]
Works without.
